openapi: 3.0.1
info:
  description: Easily and directly scan and block spam security threats in input.
  title: spamapi
  version: v1
servers:
- url: /
security:
- Apikey: []
paths:
  /spam/detect/text-string:
    post:
      description: "Analyzes input content as well as embedded URLs with AI deep learnign\
        \ to detect spam, phishing and other unsafe content.  Uses 25-75 API calls\
        \ depending on model selected."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpamDetectionRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/SpamDetectionRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SpamDetectionRequest'
        description: Spam detection request
        required: false
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SpamDetectionResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionResponse'
          description: OK
      summary: Perform AI spam detection and classification against input text string
      tags:
      - SpamDetection
      x-codegen-request-body-name: body
  /spam/detect/text-string/advanced:
    post:
      description: "Analyzes input content as well as embedded URLs with AI deep learnign\
        \ to detect spam, phishing and other unsafe content.  Uses 25-100 API calls\
        \ depending on model selected."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpamDetectionAdvancedRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/SpamDetectionAdvancedRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SpamDetectionAdvancedRequest'
        description: Spam detection request
        required: false
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SpamDetectionAdvancedResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionAdvancedResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionAdvancedResponse'
          description: OK
      summary: Perform advanced AI spam detection and classification against input
        text string
      tags:
      - SpamDetection
      x-codegen-request-body-name: body
  /spam/detect/form-submission/advanced:
    post:
      description: "Analyzes form input content as well as embedded URLs with AI deep\
        \ learnign to detect spam, phishing and other unsafe content.  Uses 25-100\
        \ API calls depending on model selected."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpamDetectionAdvancedFormSubmissionRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/SpamDetectionAdvancedFormSubmissionRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SpamDetectionAdvancedFormSubmissionRequest'
        description: Spam detection request
        required: false
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SpamDetectionFormSubmissionAdvancedResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionFormSubmissionAdvancedResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionFormSubmissionAdvancedResponse'
          description: OK
      summary: Perform advanced AI spam detection and classification against a form
        submission
      tags:
      - SpamDetection
      x-codegen-request-body-name: body
  /spam/detect/file:
    post:
      description: "Analyzes input content as well as embedded URLs with AI deep learnign\
        \ to detect spam, phishing and other unsafe content.  Uses 100-125 API calls\
        \ depending on model selected.  Supported file formats include DOCX, PDF,\
        \ XLSX, PPTX, EML, MSG, JPG, PNG and WEBP."
      parameters:
      - description: Model to use; default setting is Advanced
        in: header
        name: model
        schema:
          default: Advanced
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/_spam_detect_file_post_request'
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SpamDetectionResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionResponse'
          description: OK
      summary: Perform AI spam detection and classification on an input image or document
        (PDF or DOCX)
      tags:
      - SpamDetection
  /spam/detect/file/advanced:
    post:
      description: "Analyzes input content as well as embedded URLs with AI deep learning\
        \ to detect spam, phishing and other unsafe content.  Uses 25-100 API calls\
        \ depending on model selected.  Supported file formats include DOCX, PDF,\
        \ XLSX, PPTX, EML, MSG, JPG, PNG and WEBP."
      parameters:
      - description: "Optional: Specify which AI model to use.  Possible choices are\
          \ Normal and Advanced.  Default is Advanced."
        in: header
        name: model
        schema:
          default: Advanced
          type: string
      - description: "Optional: Specify which preprocessing to Use.  Possible choices\
          \ are None, Compatability and Auto.  Default is Auto."
        in: header
        name: preprocessing
        schema:
          default: Auto
          type: string
      - description: "True if phishing should be allowed, false otherwise"
        in: header
        name: allowPhishing
        schema:
          default: false
          type: boolean
      - description: "True if unsolicited sales should be allowed, false otherwise"
        in: header
        name: allowUnsolicitedSales
        schema:
          default: false
          type: boolean
      - description: "True if promotional content should be allowed, false otherwise"
        in: header
        name: allowPromotionalContent
        schema:
          default: true
          type: boolean
      - description: "Apply a Custom Policy for Spam Enforcement by providing the\
          \ ID; to create a Custom Policy, navigate to the Cloudmersive Management\
          \ Portal and select Custom Policies.  Requires Managed Instance or Private\
          \ Cloud"
        in: header
        name: customPolicyId
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/_spam_detect_file_post_request'
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SpamDetectionAdvancedResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionAdvancedResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SpamDetectionAdvancedResponse'
          description: OK
      summary: Perform advanced AI spam detection and classification against input
        text file.
      tags:
      - SpamDetection
components:
  schemas:
    SpamDetectionAdvancedFormField:
      additionalProperties: false
      description: Form field submitted to run spam detection on
      example:
        FieldValue: "Acme, Inc."
        FieldTitle: LeadCompanyName
      properties:
        FieldTitle:
          description: Title of the field
          example: LeadCompanyName
          type: string
        FieldValue:
          description: Value of the field
          example: "Acme, Inc."
          type: string
      type: object
    SpamDetectionAdvancedFormSubmissionRequest:
      additionalProperties: false
      description: AI advanced spam detection request
      example:
        AllowPhishing: false
        InputFormFields:
        - FieldValue: "Acme, Inc."
          FieldTitle: LeadCompanyName
        - FieldValue: "Acme, Inc."
          FieldTitle: LeadCompanyName
        AllowUnsolicitedSales: false
        AllowPromotionalContent: false
      properties:
        InputFormFields:
          description: Form fields and values that you received in your form submission
          items:
            $ref: '#/components/schemas/SpamDetectionAdvancedFormField'
          type: array
        AllowUnsolicitedSales:
          description: "True if unsolicited sales should be allowed, false otherwise"
          example: false
          type: boolean
        AllowPromotionalContent:
          description: "True if promotional content should be allowed, false otherwise"
          example: false
          type: boolean
        AllowPhishing:
          description: "True if phishing should be allowed, false otherwise"
          example: false
          type: boolean
      type: object
    SpamDetectionAdvancedRequest:
      additionalProperties: false
      description: AI advanced spam detection request
      example:
        AllowPhishing: false
        CustomPolicyID: CustomPolicyID
        InputString: Buy bitcoin now!!!!
        Model: Advanced
        AllowUnsolicitedSales: false
        AllowPromotionalContent: false
      properties:
        InputString:
          description: Input text string to detect spam against
          example: Buy bitcoin now!!!!
          type: string
        Model:
          description: "Optional: Specify which AI model to use.  Possible choices\
            \ are Normal and Advanced.  Default is Advanced."
          example: Advanced
          type: string
        AllowUnsolicitedSales:
          description: "True if unsolicited sales should be allowed, false otherwise"
          example: false
          type: boolean
        AllowPromotionalContent:
          description: "True if promotional content should be allowed, false otherwise"
          example: false
          type: boolean
        AllowPhishing:
          description: "True if phishing should be allowed, false otherwise"
          example: false
          type: boolean
        CustomPolicyID:
          description: "Apply a Custom Policy for Spam Enforcement by providing the\
            \ ID; to create a Custom Policy, navigate to the Cloudmersive Management\
            \ Portal and select Custom Policies.  Requires Managed Instance or Private\
            \ Cloud"
          type: string
      type: object
    SpamDetectionAdvancedResponse:
      additionalProperties: false
      description: Result of detecting spam using AI
      example:
        ContainsSpam: true
        ContainsUnsolicitedSales: true
        ContainsPhishingAttempt: true
        SpamRiskLevel: 0.8008281904610115
        AnalysisRationale: AnalysisRationale
        CleanResult: true
        ContainsPromotionalContent: true
      properties:
        CleanResult:
          description: "True if the result is not spam (clean), and false otherwise"
          type: boolean
        SpamRiskLevel:
          description: Overall spam risk level between 0.0 and 1.0
          format: double
          type: number
        ContainsSpam:
          description: "True if the input text contains spam, false otherwise"
          type: boolean
        ContainsUnsolicitedSales:
          description: "True if the input text contains unsolicited sales, false otherwise"
          type: boolean
        ContainsPromotionalContent:
          description: "True if the input text contains promotional content, false\
            \ otherwise"
          type: boolean
        ContainsPhishingAttempt:
          description: "True if the input text contains a phishing attempt, false\
            \ otherwise"
          type: boolean
        AnalysisRationale:
          description: Rationale for why the conclusion was formed
          type: string
      type: object
    SpamDetectionFormSubmissionAdvancedResponse:
      additionalProperties: false
      description: Result of detecting spam using AI
      example:
        ContainsSpam: true
        ContainsUnsolicitedSales: true
        ContainsPhishingAttempt: true
        SpamRiskLevel: 0.8008281904610115
        AnalysisRationale: AnalysisRationale
        CleanResult: true
        ContainsPromotionalContent: true
      properties:
        CleanResult:
          description: "True if the result is not spam (clean), and false otherwise"
          type: boolean
        SpamRiskLevel:
          description: Overall spam risk level between 0.0 and 1.0
          format: double
          type: number
        ContainsSpam:
          description: "True if the input text contains spam, false otherwise"
          type: boolean
        ContainsUnsolicitedSales:
          description: "True if the input text contains unsolicited sales, false otherwise"
          type: boolean
        ContainsPromotionalContent:
          description: "True if the input text contains promotional content, false\
            \ otherwise"
          type: boolean
        ContainsPhishingAttempt:
          description: "True if the input text contains a phishing attempt, false\
            \ otherwise"
          type: boolean
        AnalysisRationale:
          description: Rationale for why the conclusion was formed
          type: string
      type: object
    SpamDetectionRequest:
      additionalProperties: false
      description: AI spam detection request
      example:
        InputString: Get free crypto now!!!
        Model: Advanced
      properties:
        InputString:
          description: Input text string to detect spam against
          example: Get free crypto now!!!
          type: string
        Model:
          description: "Optional: Specify which AI model to use.  Possible choices\
            \ are Normal and Advanced.  Default is Advanced."
          example: Advanced
          type: string
      type: object
    SpamDetectionResponse:
      additionalProperties: false
      description: Result of detecting spam using AI
      example:
        CleanResult: true
      properties:
        CleanResult:
          description: "True if the result is not spam (clean), and false otherwise"
          type: boolean
      type: object
    _spam_detect_file_post_request:
      properties:
        inputFile:
          format: binary
          type: string
      type: object
  securitySchemes:
    Apikey:
      description: Apikey
      in: header
      name: Apikey
      type: apiKey
x-original-swagger-version: "2.0"

